# dataset
dataset: DuRecDial
language: zh # zh/en
tokenize: bert
# dataloader
context_truncate: 256
response_truncate: 30
item_truncate: 100
scale: 1
# model
model: ConvBERT
# optim
loss: BinaryDSCLoss
# gamma: 5
alpha: 2
# pos_weight: 7
# smooth: 1.0
policy:
  epoch: 5
  batch_size: 8
  weight_decay: 0.01
  optimizer:
    name: AdamW
    lr: !!float 1e-5
  early_stop: true
  stop_mode: max
  impatience: 3
